# Generated by Django 5.2.12 on 2026-04-08 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="student",
            new_name="user",
        ),
    ]
