# Generated by Django 5.2.12 on 2026-04-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_rename_student_studentprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/mentors/"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/student/"
            ),
        ),
    ]
