# Generated by Django 5.2.12 on 2026-04-09 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0003_mentorprofile_avatar_studentprofile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="mentor",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="supports",
            field=models.ManyToManyField(
                related_name="students", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("mentor", "Mentor"),
                    ("support", "Support"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SupportProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/Support/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
