# Generated by Django 5.2.12 on 2026-04-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Account",
            "0004_remove_studentprofile_mentor_studentprofile_supports_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="education_level",
            field=models.CharField(default="bachelor", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="gender",
            field=models.CharField(
                choices=[("mmail", "مرد"), ("femail", "زن")],
                default="mail",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
