# Generated by Django 5.2.12 on 2026-04-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0005_mentorprofile_education_level_mentorprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "مرد"), ("female", "زن")],
                default="male",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="school_of_name",
            field=models.CharField(default="test", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "مرد"), ("female", "زن")], max_length=255
            ),
        ),
    ]
