# Generated by Django 5.2.12 on 2026-04-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Account",
            "0006_studentprofile_gender_studentprofile_school_of_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="school_of_name",
            new_name="name_of_school",
        ),
    ]
