# Generated by Django 5.2.12 on 2026-04-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0007_rename_school_of_name_studentprofile_name_of_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="supports",
        ),
    ]
