# Generated by Django 5.2.12 on 2026-04-25 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("School", "0003_studentsupport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="studentsupport",
            constraint=models.UniqueConstraint(
                fields=("student", "support"), name="unique_student_support"
            ),
        ),
    ]
