# Generated by Django 5.2.12 on 2026-05-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("School", "0004_studentsupport_unique_student_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planreport",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
