# Generated by Django 5.2.12 on 2026-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChatBotAi", "0002_alter_conversation_created_by_aimentorreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimentorreport",
            name="type",
            field=models.CharField(
                choices=[("report", "Report"), ("mentor", "Mentor")],
                default="mentor",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
